version: '3'

services:
  earning.demo.api:
    image: msorokovsky/dotnetcore-demoapp:1.0.0-earning.demo.api
    build:
      context: ./Earning.Demo.Api
      dockerfile: Dockerfile

  earning.demo.api.v2:
    image: msorokovsky/dotnetcore-demoapp:2.0.0-earning.demo.api
    build:
      context: ./Earning.Demo.Api
      dockerfile: DockerfileV2

  earning.demo.web:
    image: msorokovsky/dotnetcore-demoapp:1.0.0-earning.demo.web
    build:
      context: ./Earning.Demo.Web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  earning.demo:
    image: msorokovsky/dotnetcore-demoapp:1.0.0-earning.demo
    build:
      context: ./Earning.Demo
      dockerfile: Dockerfile